test_that("design-first Shiny interface and canonical SNFG cards are bundled", {
  app_file <- system.file("shiny", "app.R", package = "glycoPathDesign")
  app_text <- paste(readLines(app_file, warn = FALSE), collapse = "\n")
  expect_match(app_text, "Design check", fixed = TRUE)
  expect_match(app_text, "Build a pathway", fixed = TRUE)
  expect_match(app_text, "reaction_editor", fixed = TRUE)
  expect_match(app_text, "Registered N-glycan reactions", fixed = TRUE)
  expect_match(app_text, "Custom definitions", fixed = TRUE)
  expect_match(app_text, "registered_reaction_choices", fixed = TRUE)
  expect_match(app_text, "add_registered_reaction", fixed = TRUE)
  expect_match(app_text, "add_custom_reaction", fixed = TRUE)
  expect_match(app_text, "Measured class", fixed = TRUE)
  expect_match(app_text, "Upload CSV", fixed = TRUE)
  expect_match(app_text, "Panel dimension", fixed = TRUE)
  expect_match(app_text, "Forward-model fit", fixed = TRUE)
  expect_match(app_text, "Robustness & fit", fixed = TRUE)

  card_directory <- system.file("shiny", "www", "snfg_cards", package = "glycoPathDesign")
  cards <- list.files(card_directory, pattern = "[.]png$", full.names = FALSE)
  expect_equal(length(cards), 22)
  expect_setequal(sub("[.]png$", "", cards), canonical_pathway()$observed_classes)
})
